### ISSUE TITLE
Could not build module OneSignal

### ISSUE THREAD

**Issue by kferrone** [zype/zype-ios#20]
Using MacOS Sierra v-10.12 with i5 processor. 

I can't run the app because I get "Could not build module OneSignal"

In the OneSignal.h file I get "@proeprty(class)" doesn't have a class as a param. also at the very bottom I get "expected a type. " 

Any ideas what this is about?

**Comment by svetdev** [comment]
Have you installed pods successfully? OneSignal is used for Push Notification. You can comment out the code that is loading OneSignal in AppDelegate if you don't want to use this feature.
